services:
  app:
    build: .
    container_name: confservice
    ports:
      - "5000:5000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./themes:/app/themes
    restart: on-failure:5